apiVersion: v1
kind: Service
metadata:
  name: vote-service
  namespace: dilivio
spec:
  type: NodePort
  selector:
    app: vote-deployment
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 80 
      
