apiVersion: v1
kind: Service
metadata:
  name: result-service
  namespace: dilivio
spec:
  type: NodePort
  selector:
    app: result-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80