apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: dilivio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-deployment
  template:
    metadata:
      labels:
        app: worker-deployment
    spec:
      containers:
      - name: worker-container
        image: diliviosantos/k8-worker:latest
        env:
          - name: REDIS_HOST
            value: "redis-service"
          - name: DB_HOST
            value: "postgres-service"
          - name: DB_USERNAME
            value: "postgres"
          - name: DB_PASSWORD
            value: "postgres"
          - name: DB_NAME
            value: "postgres"
        resources:          
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"