apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: dilivio
spec:
  type: ClusterIP # Using ClusterIP for internal database service
  selector:
    app: postgres-deployment
  ports:
    - protocol: TCP
      port: 5432         
      targetPort: 5432 