apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: dilivio
spec:
  type: ClusterIP # Using ClusterIP for internal database service
  selector:
    app: redis-deployment
  ports:
    - protocol: TCP
      port: 6379         
      targetPort: 6379 